code refined

diff --git a/.github/workflows/liquor-license-applicant-pipeline.yml b/.github/workflows/liquor-license-applicant-pipeline.yml
--- a/.github/workflows/liquor-license-applicant-pipeline.yml
+++ b/.github/workflows/liquor-license-applicant-pipeline.yml
@@ -40,9 +40,14 @@ jobs:
         working-directory: ./scripts
         run: |
           OUTPUT=$(node getVotingMinutes.js)
-          echo "$OUTPUT"  
-          PDF_FILE=$(echo "$OUTPUT" | tail -n 1)
-          VOTING_DATE=$(echo "$OUTPUT" | tail -n 2 | head -n 1)
+
+          SUCCESS=$(echo "$OUTPUT" | jq -r '.success')
+          if [ "$SUCCESS" != "true" ]; then
+            echo "Script failed : $(echo "$OUTPUT" | jq -r '.message')"
+            exit 1 
+          fi
+          PDF_FILE=$(echo "$OUTPUT" | jq -r '.fileName')
+          VOTING_DATE=$(echo "$OUTPUT" | jq -r '.pdfDate')
           echo "pdf_file=$PDF_FILE" >> $GITHUB_OUTPUT
           echo "voting_date=$VOTING_DATE" >> $GITHUB_OUTPUT
  
